### PR TITLE
Add Redis extension

### PR DESCRIPTION
**Pull request by fgilio**
👋🏼
This should be enough to take care of https://github.com/lorisleiva/laravel-docker/issues/10, according to https://github.com/edbizarro/gitlab-ci-pipeline-php/blob/f8ee01ccb5d35c5449f921844ba16b56b115ea65/php/scripts/extensions.sh#L131-L133

### CODE REVIEW

**Comment by lorisleiva** [comment]
Awesome! Thanks for that @fgilio! 🍺

**Comment by fgilio** [comment]
🍻

**Comment by fgilio** [comment]
May be worth noting that this added the Redis extension to PHP, but there's no actual Redis service in the image 🤔

@lorisleiva do you think the issues shouldn't be closed until there's a Redis service? Maybe I'm overthinking this, you can add the service like you add MySQL

**Comment by lorisleiva** [comment]
I think so yeah. I don’t think it’s the responsibility of this image to start a redis server but at least now it can interact with one. It’s also worth noting that the predis composer package is back to being maintained so that should make life even easier when it comes to redis. ☺️

**Comment by fgilio** [comment]
Yes, that's really nice. They're are even already planning/working on PHP 8 compat  🙌

**Pull request merged**
